version: '3.8'
services:
  server:
    build:
        context: ./
        dockerfile: Dockerfile.server        
    container_name: server    
    ports:
      - '8080:8080'
  ui:
    build:
      context: ./
      dockerfile: Dockerfile.ui
    container_name: ui
    ports:
      - 4200:80
    links:
      - server